### PR TITLE
Open non-binary files with CHARACTER element type

### PR DESCRIPTION
**Pull request by ndantam**

### CODE REVIEW

**Comment by metawilm** [comment]
Hi, thanks for the PR. The file handling in CLPython is incomplete and I welcome patches.
However returning bytes when reading a file in binary mode seems to Python 3 behaviour: 
```
Python 3.5.3:
>>> f = open('/tmp/a.txt', 'rb')
>>> f.read()
b'abc\n'
```
whereas CLPython aims for Python 2 compatibility, and there the data is always returned as a string:
```
Python 2.7.13:
>>> f = open('/tmp/a.txt', 'rb')
>>> f.read()
'abc\n'```

**Comment by ndantam** [comment]
Thanks for the note on compatibility.  Can you suggest a preferred mechanism to achieve both binary and character I/O?

If data needs to always be returned as a string, would it be better to always open files with :ELEMENT-TYPE CHARACTER?  Or is it better to perform character encoding within the py-methods in builtins-file.lisp?  Or maybe a third option is a gray stream (could help python/lisp interop)?

My immediate need is just to write some text to a file, but it would be good to achieve this in the most "compatible" way possible.

**Comment by metawilm** [comment]
If you mean writing binary and text using Lisp, it seems Edi's [flexi-streams](https://edicl.github.io/flexi-streams/) supports that.

Within Python 2 you might want to use `bytearray` like:
```
f.write(bytearray([1,2,3]))
data = bytearray(f.read())
```
CLPython does not have that type `bytearray` yet, but if this would solve your problem I can add support for it. In that case please tell me the argument kind you want to use for writing bytes, like a list with integers `[1,2,3]` as above, or a string `"\x01\x02\x03"` (this is using hex escapes).

**Comment by ndantam** [comment]
I am trying to write text in CLPython:

    f = open('/tmp/a.txt','w')
    f.write("hello\n");

This did not work because the Lisp stream was opened in binary mode.  Opening the Lisp stream with character element-type (as in the pull request) would allow WRITE-STRING to work, but as you say, may not be appropriately compatible with CPython.

In CPython (2.7.13), the above text writing works when the file is opened in either binary or text mode.  Maybe there would be differences in newline conversions on some platforms.

Flexi-streams looks like a nice package and supports mixing of character and binary I/O.  Are you suggesting to use this to perform character encoding/decoding in CLPython's file implementation?

**Comment by metawilm** [comment]
I see what you mean. I just pushed a fix for file.write() to work with a string argument, keeping the byte as element-type of the underlying stream. Thanks for reporting this!

**Pull request closed without merging**
